### ISSUE TITLE
I get lines between aligned brackets

### ISSUE THREAD

**Issue by hbrls** [Nidre/VS2015-Dark-Android-Studio#1]
I do not see them in your screenshot. Do you know how to turn them off?

<img width="533" alt="screen shot 2016-01-23 at 12 18 09 am" src="https://cloud.githubusercontent.com/assets/1220476/12516147/dea059ea-c166-11e5-9af5-3e71e104bd77.png">

**Comment by hbrls** [comment]
Hey, I got the answer.

I downloaded the theme from color-themes.com, which inherits from `Default`. `Default` is a light theme and has a lot of light settings like that.

I then installed from this repo, which inherits from `Darcula`. Everything goes fine.

**Comment by Nidre** [comment]
@hbrls 

Sorry for the late reply. As far as I've understand the issue is fixed and was related to this repository. I am marking this issues as resolved. Do not hesitate to re-open if the issue still exists.

**Comment by hbrls** [comment]
@Nidre The theme at color-themes.com is not up to date.

**Comment by Nidre** [comment]
@hbrls Noted, I will try to contact the website for an update, thanks for letting me know!
