### ISSUE TITLE
Setting file does not work in latest IntelliJ community

### ISSUE THREAD

**Issue by HamedSalameh** [Nidre/VS2015-Dark-Android-Studio#10]
hi
followed the instructions your posted, but the settings file is not valid.

**Comment by Kendos-Kenlen** [comment]
Try to download the [color scheme](https://github.com/Nidre/VS2015-Dark-Android-Studio/blob/master/colors/VS2015-Dark.icls) directly and import it in IntelliJ.

**Comment by fastestdevalive** [comment]
I just used the settings  file. It works absolutely fine.
